name: blue_slam
geometry:
  l: 0.0
  r: 0.067
  d: 0.174
  camera: [0, 0, 0]
  imu: [0, 0, 0]
#  imu: [0, 0, 4.4cm - 1cm + 3mm]
#  camera: [7mm + 4cm, 8.4cm,,5cm + 3mm + 3mm]
battery:
  design_capacity: 1.3
  serial_number: '2200011456159'
motors:
  # True Gear Ratio (22×20×22×22×23) / (12×12×10×10×10) ~= 34.014
  gear_ratio: 34.014
  encoder_ratio: 12.0
  max_rpm: 290
  min_volts: 0.0
  max_volts: 12.0
controller:
  leds: 3
  buttons: 3
  notes: 16
  cmd_mag: 400
  motor_sample_rate: 50.0
  button_sample_rate: 4.0
  battery_sample_rate: 0.2


