#!/usr/bin/env python

import yaml
import rospy

from controller import AStar

if __name__ == "__main__":
    try:
        rospy.init_node('lowlevel_controller')

        params = None
        param_path = rospy.get_param('~lowlevel_config_path')
        with open(param_path, 'r') as f:
            params = yaml.load(f.read())
        rospy.set_param(params['controller']['root_topic'], params)

        robot = AStar(params)
        rate = rospy.Rate(params['controller']['supervise_rate'])
        while not rospy.is_shutdown():
            robot.supervise()
            rate.sleep()
        robot.shutdown()

    except rospy.ROSInterruptException:
        pass
