#!/usr/bin/env python

import yaml
import rospy

from controller import BlueSlam

if __name__ == "__main__":
    try:
        rospy.init_node('blueslam_controller')

        params = None
        param_path = rospy.get_param('~robot_config_path')
        with open(param_path, 'r') as f:
            params = yaml.load(f.read())
        rospy.set_param(params['robot_name'], params)

        robot = BlueSlam(params)
        rate = rospy.Rate(params['controller']['update_rate'])
        while not rospy.is_shutdown():
            robot.update(rospy.get_rostime(), rate)
            rate.sleep()

    except rospy.ROSInterruptException:
        pass
