#!/usr/bin/env python

import yaml
import rospy

from controller import BlueSlam

if __name__ == "__main__":
    try:
        rospy.init_node('blue_slam_controller')

        robot_name = rospy.get_param('~robot_name')
        robot = BlueSlam(robot_name)
        rate = rospy.Rate(rospy.get_param(robot_name + '/controller/update_rate'))
        while not rospy.is_shutdown():
            robot.update(rospy.get_rostime(), rate)
            rate.sleep()

    except rospy.ROSInterruptException:
        pass
